@startuml

title __SUBJECT's Class Diagram__\n

  namespace learningapp {
    namespace dtos {
      namespace subject {
        class learningapp.dtos.subject.SubjectDto {
            - id : UUID
            - name : String
            {static} - serialVersionUID : long
            - topicDtos : List<TopicDto>
            + SubjectDto()
            + SubjectDto()
            {static} + builder()
            + getId()
            + getName()
            + getTopicDtos()
            + setId()
            + setName()
            + setTopicDtos()
        }
      }
    }
  }
  

  namespace learningapp {
    namespace dtos {
      namespace subject {
        class learningapp.dtos.subject.SubjectDto.SubjectDtoBuilder {
            - id : UUID
            - name : String
            - topicDtos : List<TopicDto>
            + build()
            + id()
            + name()
            + toString()
            + topicDtos()
            ~ SubjectDtoBuilder()
        }
      }
    }
  }
  

  namespace learningapp {
    namespace dtos {
      namespace subject {
        class learningapp.dtos.subject.TopicDto {
            - id : UUID
            - name : String
            {static} - serialVersionUID : long
            + TopicDto()
            + TopicDto()
            {static} + builder()
            + getId()
            + getName()
        }
      }
    }
  }
  

  namespace learningapp {
    namespace dtos {
      namespace subject {
        class learningapp.dtos.subject.TopicDto.TopicDtoBuilder {
            - id : UUID
            - name : String
            + build()
            + id()
            + name()
            + toString()
            ~ TopicDtoBuilder()
        }
      }
    }
  }
  

  learningapp.dtos.subject.SubjectDto .up.|> java.io.Serializable
  learningapp.dtos.subject.SubjectDto +-down- learningapp.dtos.subject.SubjectDto.SubjectDtoBuilder
  learningapp.dtos.subject.TopicDto .up.|> java.io.Serializable
  learningapp.dtos.subject.TopicDto +-down- learningapp.dtos.subject.TopicDto.TopicDtoBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
