@startuml
!pragma graphviz_dot jdot

[*] --> Pending
Pending --> Validated
Pending --> Invalidated
Pending ---> Requested_changes

Requested_changes --> Pending
Requested_changes --> Validated
Requested_changes --> Invalidated

Validated --> [*]
Invalidated --> [*]

@enduml
