@startuml

title __APIS's Class Diagram__\n

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.AuthenticationApi {
          {abstract} + login()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.NotificationApi {
          {abstract} + getNotifications()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.ProfessorApi {
          {abstract} + getAllQuestions()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.QuestionApi {
          {abstract} + createQuestion()
          {abstract} + getAllPendingQuestionsByTopic()
          {abstract} + getNotificationsCount()
          {abstract} + getQuestion()
          {abstract} + updateQuestion()
          {abstract} + validateQuestion()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.StudentApi {
          {abstract} + getAllQuestions()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.SubjectApi {
          {abstract} + addSubject()
          {abstract} + addTopicToSubject()
          {abstract} + getAllSubjects()
          {abstract} + getSubject()
          {abstract} + updateSubject()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.TestApi {
          {abstract} + addTest()
          {abstract} + getTest()
          {abstract} + getTestDifficulties()
          {abstract} + getTests()
          {abstract} + gradeTest()
      }
    }
  }
  

  namespace learningapp {
    namespace apis {
      interface learningapp.apis.UserApi {
          {abstract} + getUser()
          {abstract} + updateUser()
          {abstract} + validatePassword()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
