@startuml

title __EXCEPTIONS's Class Diagram__\n

  namespace learningapp {
    namespace exceptions {
      class learningapp.exceptions.ExceptionMessages {
          {static} + DUPLICATE_SUBJECT : String
          {static} + INVALID_TRANSITION_ERROR : String
          {static} + STRING_TO_UUID_ERROR : String
          {static} + STUDENT_NOT_FOUND : String
          {static} + SUBJECT_NOT_FOUND : String
          {static} + TEST_ANSWER_NOT_FOUND : String
          {static} + TEST_NOT_FOUND : String
          {static} + TEST_QUESTION_NOT_FOUND : String
          {static} + TOPIC_NOT_FOUND : String
          {static} + USER_INVALID_PASSWORD : String
          {static} + USER_NOT_FOUND : String
      }
    }
  }
  

  namespace learningapp {
    namespace exceptions {
      class learningapp.exceptions.LearningappRestControllerAdvice {
          {static} - log : Logger
          + handleException()
          + handleException()
          + handleException()
          + handleException()
          + handleException()
      }
    }
  }
  

  namespace learningapp {
    namespace exceptions {
      class learningapp.exceptions.ResponseEntity {
          + message : String
          {static} + builder()
          ~ ResponseEntity()
      }
    }
  }
  

  namespace learningapp {
    namespace exceptions {
      class learningapp.exceptions.ResponseEntity.ResponseEntityBuilder {
          - message : String
          + build()
          + message()
          + toString()
          ~ ResponseEntityBuilder()
      }
    }
  }
  

  learningapp.exceptions.ResponseEntity +-down- learningapp.exceptions.ResponseEntity.ResponseEntityBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
