@startuml

title __SERVICES's Class Diagram__\n

  namespace learningapp {
    namespace services {
      interface learningapp.services.NotificationService {
          {abstract} + getAllNotifications()
          {abstract} + saveNotification()
      }
    }
  }
  

  namespace learningapp {
    namespace services {
      interface learningapp.services.QuestionService {
          {abstract} + addTestQuestion()
          {abstract} + getAllQuestionForProfessor()
          {abstract} + getAllQuestionForStudent()
          {abstract} + getAllQuestionsByTopic()
          {abstract} + getNotificationsCount()
          {abstract} + getQuestion()
          {abstract} + updateTestQuestion()
          {abstract} + validateQuestion()
      }
    }
  }
  

  namespace learningapp {
    namespace services {
      interface learningapp.services.SubjectService {
          {abstract} + addSubject()
          {abstract} + addTopicToSubject()
          {abstract} + getAllSubjects()
          {abstract} + getSubject()
          {abstract} + updateSubject()
      }
    }
  }
  

  namespace learningapp {
    namespace services {
      interface learningapp.services.TestService {
          {abstract} + addTest()
          {abstract} + getTest()
          {abstract} + getTestDifficulties()
          {abstract} + getTests()
          {abstract} + gradeTest()
      }
    }
  }
  

  namespace learningapp {
    namespace services {
      interface learningapp.services.UserService {
          {abstract} + checkPassword()
          {abstract} + getUser()
          {abstract} + login()
          {abstract} + updateUser()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
