@startuml

title __REPOSITORIES's Class Diagram__\n

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.NotificationRepository {
          {abstract} + findAllByUserAndWasSeenFalse()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.NotificationUserRepository {
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.ProfessorRepository {
          {abstract} + findAllByTopic()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.StudentRepository {
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.SubjectRepository {
          {abstract} + findAllByOrderByName()
          {abstract} + findByName()
          {abstract} + getAllSubjectNames()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.TestAnswerRepository {
          {abstract} + deleteAllByQuestion()
          {abstract} + findAllCorrectAnswersForQuestion()
          {abstract} + findByQuestion()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.TestQuestionRepository {
          {abstract} + findAllByProfessorAndStatus()
          {abstract} + findAllByStudentAndStatus()
          {abstract} + findAllByTopicAndStatus()
          {abstract} + findByIdAndTopicId()
          {abstract} + getNotificationsCountForProfessor()
          {abstract} + getNotificationsCountForStudent()
          {abstract} + selectQuestionsHavingDifficulty()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.TestRepository {
          {abstract} + getAllBySubject()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.TopicRepository {
          {abstract} + findAllBySubjectOrderByName()
          {abstract} + findAllContainingNumber()
      }
    }
  }
  

  namespace learningapp {
    namespace repositories {
      interface learningapp.repositories.UserRepository {
          {abstract} + findByUsername()
          {abstract} + findByUsernameAndPassword()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
